name: GetPing
version: 1.0.0
api: [3.0.0, 4.0.0]
load: POSTWORLD
description: Automatic Latency Measurement
commands:
    getping:
        description: show latency infomration
        usage: "/getping"

permissions:
    getping.cmd:
        default: true
        description: "Show latency information"
